import circular_linked_list as cll

words = cll.CircularLinkedList()
words.append('eggs')
words.append('spam')
words.append('sausage')
words.append('bacon')
words.append('eggs')
print(words.search('sausage'))
words.append('spam')
words.append('spam')
print(words)
words.remove_duplicates()
print(words)
words.append_at_location('new', 2)
print(words)
words.__delitem__(3)
print(words)
print(words.search('sausage'))
words.__delitem__(0)
print(words)
words.__delitem__(len(words) - 1)
print(words)

